export { loadSpec } from "./spec/loadSpec.js";
export type { SpecIR } from "./spec/schema.js";
export { generateScaffold } from "./generator/scaffold/index.js";
export { buildPlan } from "./generator/plan.js";
export { generateDb } from "./generator/db/index.js";
export { buildDbPlan } from "./generator/db/planDb.js";
export { generateCommands } from "./generator/commands/index.js";
export { buildCommandsPlan } from "./generator/commands/planCommands.js";
export { generateBusiness } from "./generator/business/index.js";
export { buildBusinessPlan } from "./generator/business/planBusiness.js";
export { generateUIA } from "./generator/ui/index.js";
export { generateUIB } from "./generator/ui/index.js";
export { buildUIAPlan } from "./generator/ui/planUIA.js";
export { buildUIBPlan } from "./generator/ui/planUIB.js";
export { classifyPath, type Zone } from "./generator/zones.js";
export { makeUnifiedDiff } from "./generator/diff.js";
export { applyPlan } from "./generator/apply.js";
export type { FileWriteMode, Plan, PlanAction, PlanActionType } from "./generator/types.js";
